from enum import Enum

class PipelineTask(Enum):
    REMOVEHTMLTAG = 1,
    CONVERTTOLOWERCASE = 2,
    REMOVENUMBER = 3,
    CONVERTNUMERICALVALUES = 4,
    REMOVEPUNCTUATION = 5,
    REMOVEWHITESPACE =6,
    REMOVESTOPWORDS = 7,
    APPLYSTEMMING = 8,
    APPLYLEMMATIZATION = 9


