from enum import Enum

class TaskReference(Enum):
    REMOVEHTMLTAG = 1,
    CONVERTTOLOWERCASE = 2,
    REMOVENUMBER = 3,
    CONVERTNUMERICALVALUES = 4,
    REMOVEPUNCTUATION = 5,
    REMOVEWHITESPACE =6,
    TOKENIZE = 7,
    REMOVESTOPWORDS = 8,
    APPLYSTEMMING = 9,
    APPLYLEMMATIZATION = 10


